name: webhook
channels:
  - defaults
  - conda-forge
dependencies:
  - python >=3.13,<3.14
  - awslambdaric >=3.1,<4
  - aws-lambda-powertools >=3.23,<4
  - boto3 >=1.40,<2
  - pydantic >=2,<3
  - pydantic-settings >=2,<3